### ISSUE TITLE
Relay-angular-plugin does not read relay.config.js

### ISSUE THREAD

**Issue by waldogit** [morrys/relay-angular#21]
Relay-angular-plugin does not read relay.config.js. One of the consequences is that angular-relay does not properly handle project setups where the angular server uses parent node_modules (like when using Nx)
For devs aspiring to use relay-angular, a quick fix is to change the index.js in the installed node_modules from
   line 10: `RelayConfig = eval('require')('relay-config');`
into
   line 10: ` RelayConfig = require("/absolute/path/to/relay.config.js");`

**Comment by morrys** [comment]
Hi @waldogit,
could you give me more details about your problem?

In the [example project](https://github.com/morrys/relay-angular/tree/master/examples/todos) I created the relay.config.js file reads correctly

**Comment by waldogit** [comment]
Hi  Lorenzo,

I was able to run your example without any worries.

I am having a setup where I use Nx from Narwal (https://github.com/nrwl/nx)
It supports an application cache across your entire application, of which
the angular project is one of the apps. And then they have a setup where
the package.json and the node_modules is shared across your apps. In such a
setup, I was unable to run the angular project because
your plugin generates the locations of the generated .graphql files
relative to the component but it somehow is off by 2 levels ('../../'.
I noticed that the plugin swallows exceptions in case the config can not be
read. When I changed that (just in the installed node_modules, like I
described in the issue) then the problem is fixed.
I noticed that relay.config has a way of reading the config file using
cosmiconfig. Is there a way you can use that way of reading the
relay.config.js?

Other than that I am very pleased with what you did, Lorenzo. Quite an
achievement and i.m.o. very useful to be able to leverage the relay way of
graphql in an angular context.

Bravo!

Waldo auf der Springe

**Comment by waldogit** [comment]
Lorenzo,

If you like me to, I can make a little sandbox project on github using Nx
to showcase the problem?

Kind regards,

Waldo auf der Springe

**Comment by morrys** [comment]
@waldogit it is always a pleasure to meet people who try new libraries and open issues to help improve them :)

To better analyze your problem, the example project would be very useful :)

**Comment by waldogit** [comment]
Hi Lorenzo,

I made an attempt to port your example to an Nx setup, but I failed to get
the babel plugin working. So i get the graphql invariant violation
exception and found no way to solve that. It is still a quick and dirty
setup, where I did not clean up the default Nestjs dependencies. That
example is here: https://github.com/waldogit/relay-angular-config
If you are able to solve the violation, my expectation is that then you
will see the plugin failing, as it generates faulty imports for the
.graphql files ('/../..' should be stripped off).
And those I can fix by tampering with the installed relay-angular-plugin.

I have some other questions for you:
I notice you switched off aot: is that a requirement? That is a serious
limitation :-(
Can the fragmentRefs come in in another way then as @Input? I would like to
pass the fragmentRef as an angular route param. Can i resolve that route
param in ngOnInit, or will that be too late for the fragmentDecorator
function?

If you can find some time to help out, that would be great :-)

Kind regards,

Waldo auf der Springe

**Comment by morrys** [comment]
> I notice you switched off aot: is that a requirement? That is a serious limitation :-(

I honestly have not tried compiling aot in case there were any problems we could try to fix them!

> Can the fragmentRefs come in in another way then as @input? I would like to
> pass the fragmentRef as an angular route param. Can i resolve that route
> param in ngOnInit, or will that be too late for the fragmentDecorator
> function?

yes, you can do it


As for your sample project, I'll do some tests as soon as possible (I'm on vacation now) :)

**Comment by morrys** [comment]
@waldogit I tried your sample project and i created a PR https://github.com/waldogit/relay-angular-config/pull/1 which allows it to be started.

Let me know what you think.

Lorenzo

**Comment by waldogit** [comment]
Hi Lorenzo,
Thank you for your swift action :-)
I tried your fix branch but I still get the same result. How do you start
the application? From the application root I start the gql server with: 'nx
serve api' and then the ng server with 'nx serve relay-angular-config'. The
browser shows a frozen white page and the console reports the graphql
invariant violation (plus now a bunch of warnings about unused graphql.ts
imports - another sign that the babel transformation did not happen).
Besides this, I was wondering:
Does relay-angular allow you to bundle the fragments of a tree of
components into a single roundtrip? In your example, the answer is yes
because the query itself is resolvable from the query's own fragmentrefs.
But let's say I have a subcomponent that gets some ID from a route param.
Then I face 2 problems:1) AFAIK I should not pass a fragment ref, but an
argument definition. But that is not included in your API, is it?2) I guess
the roundtrip should be issued via a Query decorator, but how does that
query component know about the fragment of the other sub component? If I
look into the code, In react (of which i have 0 experience) there is
https://github.com/facebook/relay/blob/master/packages/react-relay/ReactRelayFragmentContainer.js.
Ideally there would  be an equivalent of that in relay-angular - but that
does not sound simple. The alternative is that the application keeps track
of those. That becomes cumbersome: if a route param has several route
targets as children, then all those children need to reference that
fragment.

Regards.

Waldo

**Comment by morrys** [comment]
Hi @waldogit,
I ran the application with `yarn start (ng serve --plugin relay-angular-plugin)` in the root.
Otherwise, `nx serve relay-angular-config --plugin relay-angular-plugin` is fine too.

I didn't understand the use case described here:

> In your example, the answer is yes
> because the query itself is resolvable from the query's own fragmentrefs.
> But let's say I have a subcomponent that gets some ID from a route param.
> Then I face 2 problems:1) AFAIK I should not pass a fragment ref, but an
> argument definition. But that is not included in your API, is it?2) I guess
> the roundtrip should be issued via a Query decorator, but how does that
> query component know about the fragment of the other sub component? If I
> look into the code, In react (of which i have 0 experience) there is
> https://github.com/facebook/relay/blob/master/packages/react-relay/ReactRelayFragmentContainer.js.
> Ideally there would  be an equivalent of that in relay-angular - but that
> does not sound simple. The alternative is that the application keeps track
> of those. That becomes cumbersome: if a route param has several route
> targets as children, then all those children need to reference that
> fragment.

Can you show me in the sample project?

Thanks

**Comment by waldogit** [comment]
Hi Lorenzo, I am glad you elaborated how you started the apps, that pinpointed a huge blind spot on my part; things work correctly now :-) With that, I think the issue I described can be closed.

The other points I mention along the way could maybe be adressed in a new issue, but until then:
I added a commit to my sample project, it's pretty artificial but I hope it does get its point across. I added some explanation to the commit, let me know if it makes sense to you.

**Comment by waldogit** [comment]
It works, as you said! I am glad there is no race condition with resolving the fragment id. But the remaining issue is: pressing the 'Combine' leads to 2 roundtrips, one for the combinedQuery and one for the todoQueryQuery. How can they be bundled into a single roundtrip?
